version: "3.7"

services:
  rabbitMQ:
    image: rabbitmq:3-management
    container_name: rabbit
    restart: always
    ports:
      - "5672:5672"
      - "15672:15672"

#docker run -d -p 5672:5672 -p 15672:15672 --name my-rabbit rabbitmq:3-management