spring:
  application:
    name: customer
  datasource:
    driver-class-name: org.postgresql.Driver
    name: main-postgresql
    url: jdbc:postgresql://localhost:5432/customer-db
    username: us
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  config:
    import: "optional:configserver:${config.uri:http://localhost:8888}"

server:
  port: 8081

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eureka.url:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

