version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    networks:
      - postgres
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "9090:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: reklaabderrahim@hotmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - postgres
    volumes:
      - pgadmin-data:/var/lib/pgadmin

networks:
  postgres:
    driver: bridge
    
volumes:
  local_pgdata:
  pgadmin-data: