spring:
  application:
    name: notification
  config:
    import: "optional:configserver:${config.uri:http://localhost:8888}"

server:
  port: 8787

twilio:
  account_sid: "${twilio_account_sid:sid}"
  auth_token: "${twilio_auth_token:token}"
  phone_number: "${twilio_phone_number:+10000000000}"
  phone_number_receiver: "${twilio_phone_number_receiver:+330000000}"

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eureka.url:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"
