eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${eureka.url:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: equipment
          uri: lb://equipment
          predicates:
            - Path=/equipment/**
          filters:
            - StripPrefix=1
        - id: consumer
          uri: lb://customer
          predicates:
            - Path=/consumer/**
          filters:
            - StripPrefix=1
server:
  port: 5555

management:
  endpoints:
    web:
      exposure:
        include:
          - mappings
          - env
          - health
          - info