spring:
  cloud:
    config:
      server:
        git:
          uri: ${HOME}/dev/config-server-repo
          default-label: master
  application:
    name: config-server
server:
  port: ${host.port:8888}